### ISSUE TITLE
pod spec lint error

### ISSUE THREAD

**Issue by bsudekum** [mapbox/MapboxNavigation.swift#19]
```
bobby MapboxNavigation.swift (master) $ pod spec lint

 -> MapboxNavigation.swift (0.0.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `MapboxDirections.swift` depended upon by `MapboxNavigation.swift`) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

/cc @frederoni @1ec5

**Comment by bsudekum** [comment]
It looks like you cannot specify a git/ git branch/ or commit for this value. I think as a fix, we'll require users to add two dependencies, this and MapboxDirections.swift

**Comment by 1ec5** [comment]
That’s correct. We need to publish the MapboxDirections.swift pod to CocoaPods.org. Moreover, we need to release a version of MapboxDirections.swift written in Swift 3. The current release is written in Swift 2, which is incompatible with this library.
