### ISSUE TITLE
MBRouteStep

### ISSUE THREAD

**Issue by osalginci** [mapbox/MapboxNavigation.swift#23]
The Property maneuverType is inaccessible from Objective C because of being optional. 

MBRouteStep.swift
 open let maneuverType: ManeuverType

**Comment by frederoni** [comment]
Thank you for reaching out.

You're right about manueverType being inaccessible in Objective-C but optional properties bridges fine to Objective-C as nullables. However, Int subclasses or CustomStringConvertible won't bridge. I suggest we translate ManeuverType to an extensible string enum in Objective-C.

**Comment by frederoni** [comment]
Thanks for reaching out.
MBRouteStep is actually part of [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift) and it seems to bridge fine (`@property (nonatomic, readonly) enum MBManeuverType maneuverType;`) to Objective-C here. Do you import MapboxDirections and not just MapboxNavigation?

**Comment by osalginci** [comment]
Just MapboxNavigation . Also , I am new on swift so I would like to know where you implement direction arrow ? That I would like to change image. ?

**Comment by frederoni** [comment]
You'll have to switch on `routeStep.direction`

```swift
switch direction {
    case .right:
        imageView.image = UIImage(named: "right_arrow")
    case .slightRight:
        imageView.image = UIImage(named: "slight_right_arrow")
    …
}
```

You can also use MBRouteStep's `initialHeading` and `finalHeading` to calculate the direction and draw the exact representation in `draw(_:)`

**Comment by osalginci** [comment]
Hi, Thanks for a quick replay. I think there has been a misunderstanding. I am trying to replace this image. I want to play with coordinates of this direction images position.
<img width="87" alt="screen shot 2017-01-25 at 17 29 46" src="https://cloud.githubusercontent.com/assets/25150108/22294325/ecee1ad4-e323-11e6-90bb-071aa3797c0d.png">

**Comment by frederoni** [comment]
Aha, sorry about that.
You'll have to subclass `MGLUserLocationAnnotationView` and implement `-mapView:viewForAnnotation:` 

```swift
func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
    if annotation is MGLUserLocation {
        let identifier = "userAnnotationIdentifier"
        var annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: identifier) as? MyUserLocationAnnotationView
        if annotationView == nil {
            annotationView = MyUserLocationAnnotationView(reuseIdentifier: identifier)
        }

        return annotationView
    }
    // ...
}
```

**Comment by osalginci** [comment]
Excellent. Thank you very much. I am trying to change the image and also keep user on the path polyline. So for   I need to add MGPointAnnotation to map and place it do closestdistance coordinate on the map right ?
