### ISSUE TITLE
Carthage problem

### ISSUE THREAD

**Issue by danrudolf1** [mapbox/MapboxNavigation.swift#37]
I'm not totally proficient with carthage but when I add the repo to m Cartfile like listed it takes down the Podfiles as well and prevents carthage from building with the Podfile.lock sync error. I had to go into the project directory that carthage pulled down and do pod install there before I could build the framework from my project directory.

**Comment by frederoni** [comment]
Thanks for reporting this. Carthage will use the latest version/tag if no branch is specified. So what's happening here is that you fetch v0.0.4 which only supports CocoaPods.
This issue will be fixed automatically when we make a new release.
 In the meantime, you can specify the branch "master" as a workaround 
```
github "mapbox/MapboxNavigation.swift" "master"
```
or use CocoaPods.
