### ISSUE TITLE
bike routing?

### ISSUE THREAD

**Issue by emiltin** [mapbox/MapboxNavigation.swift#38]
has this been tested with bike routing? things like when you provide guidance messages might have to be adjusted - is this possible?

**Comment by bsudekum** [comment]
@emiltin I think it would work pretty okay for cyclists, but it's heavily optimized for car navigation. Overall, many hard coded constants would have to be optimized a bit. I think there are also some biking specific changes we could add too.

As a quick win, you could change the profile used here https://github.com/mapbox/MapboxNavigation.swift/blob/master/Example/Swift/ViewController.swift#L142 to the bike profile. 

I've personally used this on my bike a few times without issues.

**Comment by emiltin** [comment]
how would we use our own osrm server? we run three different bike profiles.

**Comment by bsudekum** [comment]
@emiltin we rely on a lot of Mapbox APIs here, most notably [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift). If you can conform your response to look more like a [`Route`](https://github.com/mapbox/MapboxDirections.swift/blob/master/MapboxDirections/MBRoute.swift), you should be able to use your own servers.

**Comment by emiltin** [comment]
you mean i cannot connect to my own OSRM server? is it because the mapbox directions api wraps the osrm response with additional data?

**Comment by bsudekum** [comment]
@emiltin Correct. And these additions trickle down into MapboxDirections.swift which is used heavily here.

**Comment by emiltin** [comment]
hmmm. are the tools to modifying osrm response into the right format open sourced?

**Comment by emiltin** [comment]
i would suggest not hardcoding values that optimize for car routing, that limits the usefulness of the code when you want to provide routing for cycling, walking, etc.

**Comment by 1ec5** [comment]
#82 added separate thresholds for cycling and walking and made them configurable. Please try out the changes and open a new issue if anything can be refined further. Thanks!

**Comment by emiltin** [comment]
thanks!
