### ISSUE TITLE
Index out of bounds when creating RouteController object

### ISSUE THREAD

**Issue by Victorgf87** [mapbox/MapboxNavigation.swift#40]
Hello, I am trying to use your SDK in my application.
I first create a route with 
`
directions.calculate(options) { (waypoints, routes, error) in
`
So I have a correct Route object, but when I do
`
RouteController.init(route: route)
`
it crashes, but the only output I get is 
`
fatal error: Index out of range
2017-01-31 12:53:51.629455 fashioncompass[1172:472618] fatal error: Index out of range
`
Do you know why would it be? 
Is there a way to show a debug trace?

Thanks for your help :)

**Comment by frederoni** [comment]
You'll find the trace in the debug navigator (<kbd>⌘</kbd><kbd>6</kbd>)
Can you show a snippet of your code inside the directions closure?
Do you get the same error when you run the examples?

**Comment by bsudekum** [comment]
Also reference example code for initializing: https://github.com/mapbox/MapboxNavigation.swift/blob/master/Example/Swift/ViewController.swift#L202

**Comment by Victorgf87** [comment]
Thank you, I will check everything and tell you if I could make it. I couldn't work on this in all this time. 
Thanks for your support!
