### ISSUE TITLE
Resume navigation after map move?

### ISSUE THREAD

**Issue by danrudolf1** [mapbox/MapboxNavigation.swift#41]
I might have missed it in the source, but is there any way to determine the navigation state after the user moves the mapView? The userlocation marker changes back to a default location marker, so I would want to simultaneously change the button label to "Resume".

**Comment by frederoni** [comment]
Almost any gesture will reset `userTrackingMode` back to `.none` but the `RouteController` will keep tracking and update your progress. You can implement `MGLMapViewDelegate`'s
```objc
-[MGLMapViewDelegate mapView:didChangeUserTrackingMode:animated:]
```
or in swift
```swift
mapView(_:didChange:animated:)
```
to get notified about changes to the mapView's `userTrackingMode`.

**Comment by bsudekum** [comment]
Documentation on this delegate method can be found [here](https://www.mapbox.com/ios-sdk/api/3.4.1/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didChangeUserTrackingMode:animated:).
