### ISSUE TITLE
Optimize thresholds for cycling and walking

### ISSUE THREAD

**Issue by emiltin** [mapbox/MapboxNavigation.swift#45]
it should be easy to use MapboxNavigation.swift for bicycle or pedestrian navigation.
instead of hardcoding values that optimize for car routing, it should be possible to change such values.

**Comment by doedje** [comment]
?? 

Use MapboxDirections.swift to get a route (car, bike or walk) and use that route in MapboxNavigation.swift to keep track of your progress on the route, receive alerts for voice guidance and detect when you move away from the route to do a reroute...

(it might be hardcoded in the example, but hey, that's just an example.....)

**Comment by emiltin** [comment]
it was based on this comment @bsudekum https://github.com/mapbox/MapboxNavigation.swift/issues/38#issuecomment-276422988

"I think it would work pretty okay for cyclists, but it's heavily optimized for car navigation. Overall, many hard coded constants would have to be optimized a bit. I think there are also some biking specific changes we could add too."

the readme files states "MapboxNavigation.swift provides an API to add turn by turn navigation to your app." so i though it was not an example app but a library you include in your own app.

i'm sorry if i misunderstand something.

**Comment by doedje** [comment]
In that case it is me misunderstanding.... sorry for the noise :/

**Comment by 1ec5** [comment]
MapboxNavigation.swift doesn’t hard-code any particular routing profile. RouteController’s initializer takes a Route object, which you’d obtain from MapboxDirections.swift using whichever routing profile you prefer. “Hard coded constants” refers to various timing and distance thresholds for determining when to recalculate a route. @bsudekum’s point is that they’re optimized for driving speeds, but that might be acceptable for cycling use cases.

**Comment by emiltin** [comment]
I'm thinking of the timing and distance threshold that you mention. It should be possible to adjust them so they fit the profile you're using. Car, bike and foot uses very different speeds and will require different thresholds to get a good navigation experience.

**Comment by 1ec5** [comment]
#82 added separate thresholds for cycling and walking and made them configurable. #83 fixed an issue where MapboxNavigation.swift would revert to the driving profile (without traffic avoidance!) upon rerouting. Please try out the changes and open a new issue if anything can be refined further. Thanks!
