### ISSUE TITLE
Pod error

### ISSUE THREAD

**Issue by Victorgf87** [mapbox/MapboxNavigation.swift#59]
Hello, I am adding NavigationUI, which I hadn't seen before, and looks very cool, via pods, and I am getting this error:
`pod 'MapboxNavigationUI.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'`
`[!] Unable to find a specification for 'MapboxNavigationUI.swift'.`

It says bitrise is failing
Just so you are aware of it :)
Thanks for everything!

**Comment by frederoni** [comment]
Hey @Victorgf87,
It's because `MapboxNavigationUI.swift.podspec` did not exist in the repo at tag/version 0.0.4.
If you want to try it out, you'll have to specify `:branch => 'master'` instead of tag.

**Comment by Victorgf87** [comment]
Now it says 
`umable to find specification for OSRMTextInstructions depdended upon MapboxNavigationUI.swift`

**Comment by frederoni** [comment]
Oh, sorry about that. We need to put that in the documentation. OSRMTextInstructions is not yet pushed to CocoaPods so the dependency won't load unless you add it to your Podfile manually:

```ruby
pod 'OSRMTextInstructions', :git => 'git@github.com:Project-OSRM/osrm-text-instructions.swift.git', :commit => 'bdd962bf5593f951bbbbd26435f732a829dacda7'
```

**Comment by Victorgf87** [comment]
Thanks, @frederoni it's working now. I got one more question: is it possible to add functionality to the cancel button? or is there any callbacks?

**Comment by frederoni** [comment]
That's great @Victorgf87 

Yes, you can implement `RouteViewControllerDelegate` to get an update when the cancel button is tapped.

```swift
func routeViewControllerDidCancelNavigation(routeViewController: RouteViewController) {
  // Manually dismiss the routeViewController        
}
```
Don't forget to set `routeViewController.navigationDelegate = self` where you instantiate the NavUI. This is not in the example yet as the API is still being refined for the initial release.

**Comment by Victorgf87** [comment]
Perfect, it looks like it's working.
Now, I have the feeling that the arrow marker doesn't move as I do. When I move the phone, the arrow doesn't change its direction, maybe I'm missing something?
I'm using the code here
[https://github.com/mapbox/MapboxNavigation.swift/blob/master/Examples/Swift/ViewController.swift](url)

Thanks, as always, for your attention and help, we appreciate it a lot :)

**Comment by frederoni** [comment]
It's currently optimized for car navigation, which means the `userTrackingMode` of the map is set to `followWithCourse`. This won't update the arrow unless you're getting location updates. What you are looking for is `followWithHeading` which is a common tracking mode for navigating while walking. You can change this manually now already but implementing support for this is something we will be focusing on in the near future.

**Comment by Victorgf87** [comment]
Cool, thank you, @frederoni , you are the best :D
If I am allowed to suggest, for instance, if I turn the phone to the right, and then to the left, it does all the spin to the right instead of doing it to the left. I think I will be posting new messages about it soon, but now I got all I needed, thank you very much for your work :D
