### ISSUE TITLE
Build Failed when run 'carthage update --platform iOS`

### ISSUE THREAD

**Issue by xincc** [mapbox/MapboxNavigation.swift#67]
*** Building scheme "OSRMTextInstructions" in OSRMTextInstructions.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/baidu/Desktop/Playground/MapboxNavigation.swift/Carthage/Checkouts/osrm-text-instructions.swift/OSRMTextInstructions.xcodeproj -scheme OSRMTextInstructions -configuration Release -derivedDataPath /Users/baidu/Library/Caches/org.carthage.CarthageKit/DerivedData/osrm-text-instructions.swift/bdd962bf5593f951bbbbd26435f732a829dacda7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

**Comment by xincc** [comment]
/Users/baidu/Desktop/Playground/MapboxNavigation.swift/Carthage/Checkouts/osrm-text-instructions.swift/OSRMTextInstructions/OSRMTextInstructions.swift:2:8: error: no such module 'MapboxDirections'
import MapboxDirections
       ^

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler

**Comment by linjinzhu** [comment]
➜  MapboxNavigation-example git:(master) ✗ carthage build
*** xcodebuild output can be found in /var/folders/_f/7hrfsspx7f59nz___0x_l70m0000gp/T/carthage-xcodebuild.aB183w.log
*** Building scheme "AWSPolly" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "Polyline" in Polyline.xcodeproj
*** Building scheme "PolylineMac" in Polyline.xcodeproj
*** Building scheme "PolylineWatch" in Polyline.xcodeproj
*** Building scheme "PolylineTV" in Polyline.xcodeproj
*** Building scheme "OSRMTextInstructions" in OSRMTextInstructions.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/linjinzhu/Documents/workspace/ios/MapboxNavigation-example/Carthage/Checkouts/osrm-text-instructions.swift/OSRMTextInstructions.xcodeproj -scheme OSRMTextInstructions -configuration Release -derivedDataPath /Users/linjinzhu/Library/Caches/org.carthage.CarthageKit/DerivedData/osrm-text-instructions.swift/bdd962bf5593f951bbbbd26435f732a829dacda7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_f/7hrfsspx7f59nz___0x_l70m0000gp/T/carthage-xcodebuild.aB183w.log

**Comment by frederoni** [comment]
@xincc 
This seems to be a bug in Carthage that we haven't been able to track down yet.
Somehow the build order of the dependencies gets mixed up.
A workaround that we currently use is to specify the master branch of MapboxDirections.swift instead of the latest 0.8. (There's no changes between 0.8 and master currently)
Put
`github "mapbox/MapboxDirections.swift" "master"`
at the top of you Cartfile and it should run.

@linjinzhu 
Some of the underlying dependencies support ⌚️watchOS and 📺tvOS but Navigation and NavigationUI only support 📱iOS so far. Pass `--platform ios` along with every carthage command to speed up the build process. As for the failure, see the answer above^.

**Comment by frederoni** [comment]
The build order seems to become an issue when a dependency is downloaded as a pre-built binary but underlying dependencies are built from source, which is the case for MapboxDirections.swift.

To overcome this, use the `--no-use-binaries` flag
`carthage update --platform ios --no-use-binaries`

/cc @1ec5 @bsudekum

**Comment by 1ec5** [comment]
Looks like we'll need to remove the binaries from the latest MapboxDirections.swift release. (Those binaries can be useful to developers who aren't using a package manager, but distributing binary Swift frameworks isn't officially supported anyways.)

**Comment by 1ec5** [comment]
Instead of removing the binaries, I’ve renamed them to remove “.framework” from the names. According to [this documentation](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file), Carthage only opens attachments with “.framework” in the name. Can you try again?

**Comment by bsudekum** [comment]
Fixed this issue https://github.com/mapbox/MapboxNavigation.swift/issues/67#issuecomment-285269141. `carthage update --platform ios ` should work fine now.

**Comment by jesuasir007** [comment]
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Volumes/Carthage/Checkouts/EthereumKit/EthereumKit.xcodeproj -scheme EthereumKit -configuration Release -derivedDataPath /Users/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/EthereumKit/1.0.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nc/_cswghbx2gdg0tx4j8xfz2mc0000gn/T/EthereumKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Volumes/ios/new2018/ethereumbtc/bankTRON/Carthage/Checkouts/EthereumKit)

**Comment by frederoni** [comment]
@jesuasir007 It looks like you're running carthage from a mounted readonly image which causes it to crash when writing cache files. Can you post the output of `which carthage` and `carthage version`?

**Comment by jesuasir007** [comment]
Insert github "yuzushioh/EthereumKit" to your Cartfile.
Run carthage update --platform ios.


check now please

**Comment by jesuasir007** [comment]
i have used the current carthage  package  file     release version is  0.29.0 - Great Groove

**Comment by jesuasir007** [comment]
https://github.com/yuzushioh/EthereumKit

**Comment by frederoni** [comment]
> Insert github "yuzushioh/EthereumKit" to your Cartfile.

This is irrelevant as it doesn't use any of Mapbox’s libraries. Please feel free to open a new ticket if you are experiencing any issues with mapbox-navigation-ios.
