### ISSUE TITLE
Problem when installing trough cocoapods or carthage

### ISSUE THREAD

**Issue by AEnimaH** [mapbox/MapboxNavigation.swift#77]
When i install this library with both dependency managers it always fails when it's checking out osrm-text-instructions. 

cocoapods:
`[!] Unable to find a specification for OSRMTextInstructions depended upon by MapboxNavigationUI.swift`

Does anybody have the same behavior?

**Comment by AEnimaH** [comment]
When i do it trough carthage it get's stuck at `Checking out osrm-text-instructions.swift at "bdd962bf5593f951bbbbd26435f732a829dacda7"`

**Comment by AEnimaH** [comment]
I got it working using this pod file:

`platform :ios, ‘9.0’
target 'navigation' do
  use_frameworks!
  pod 'Mapbox-iOS-SDK', '~> 3.4'
  pod 'MapboxDirections.swift', '~> 0.8'
  pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'
  pod 'MapboxNavigationUI.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => 'a368a73a7575b296886ae53b7642216c167ca8e2'
  pod ‘OSRMTextInstructions’, :git => ‘https://github.com/Project-OSRM/osrm-text-instructions.swift’
end`

But know I get these compiler errors in the NavigationUI pod.
http://imgur.com/a/bj8uZ

**Comment by bsudekum** [comment]
@AEnimaH Instead of pinning to a release of MapboxNavigation.swift, can you pin it to a git commit? We are still working towards a new release. Shoud look like:

```ruby
platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.5.0-beta.3/platform/ios/Mapbox-iOS-SDK.podspec'
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => '955970285f7dee31b2c130023d7b383be51ab190'
    pod 'MapboxNavigation.swift', :git => 'git@github.com:mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
    pod 'MapboxNavigationUI.swift', :git => 'git@github.com:mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
    pod 'OSRMTextInstructions', :git => 'git@github.com:Project-OSRM/osrm-text-instructions.swift.git', :commit => 'bdd962bf5593f951bbbbd26435f732a829dacda7'
end
```

**Comment by jasonho215** [comment]
Hi @bsudekum ,

Just followed the workaround you provided here. I got another complication error when I was compiling the swift example of MapboxNavigation.swift . 
<img width="340" alt="screen shot 2017-03-17 at 5 52 39 pm" src="https://cloud.githubusercontent.com/assets/13290442/24038097/04ee3350-0b3b-11e7-955e-dc5d257227a1.png">

Here is a detailed description of the first error
<img width="296" alt="screen shot 2017-03-17 at 5 52 59 pm" src="https://cloud.githubusercontent.com/assets/13290442/24038129/16b57a62-0b3b-11e7-844d-d7d2e9067fdc.png">

Does anybody have the same error?

**Comment by AEnimaH** [comment]
Just trying the demo app with carthage is not working for me, keeps hanging at OSRM text instructions.

**Comment by xhkong** [comment]
Carthage is not working. Please fix. Thanks!

**Comment by zijiazhai** [comment]
demo is not working, please fix it soon, thank you!

**Comment by AEnimaH** [comment]
You can just take the demo code and install the dependencies using the cocoapods file in the readme. Works perfect!

**Comment by jasonho215** [comment]
@AEnimaH May I have your podfile for installation? I just tried the file in readme to install the project and I still get the IBDesignable error. Thanks

**Comment by AEnimaH** [comment]
`platform :ios, '9.0'

target 'Navigation' do
  
  use_frameworks!

  pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
  pod 'MapboxNavigationUI.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
  pod 'OSRMTextInstructions', :git => ‘git@github.com:Project-OSRM/osrm-text-instructions.swift.git', :commit => 'bdd962bf5593f951bbbbd26435f732a829dacda7'
  pod "MetaWear"

end
`

**Comment by AEnimaH** [comment]
```
platform :ios, '9.0'

target 'Navigation' do
  
  use_frameworks!

  pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
  pod 'MapboxNavigationUI.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => 'c5a637a201a3043c24e52f3e2c50a1657a8ffced'
  pod 'OSRMTextInstructions', :git => ‘git@github.com:Project-OSRM/osrm-text-instructions.swift.git', :commit => 'bdd962bf5593f951bbbbd26435f732a829dacda7'
  pod "MetaWear"

end

```

**Comment by bsudekum** [comment]
This https://github.com/mapbox/MapboxNavigation.swift/issues/77#issuecomment-287640797 is in the readme now. Re-open if you have any further issues.

**Comment by bennyty** [comment]
The build still hangs using Carthage to manage the dependencies. Same error as [this comment](https://github.com/mapbox/MapboxNavigation.swift/issues/77#issuecomment-286670221). Unfortunately, Cocoapods is not available to our team.
